# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e457596d46a0bdc52e7bbf6383011df3dd4e161d29a72358a689fca71433d1a9ae83682c51f3089d559dd523537d137ce3408f096dec93ef72f90da8027374a

test:
  secret_key_base: a96414c03085cb3137e12314520de07a117aa5428f4e326a35eefa92166f0ebd99db896aeba56fede6af7a6ed54e086f99fdadd3ab33ba0e926f47ed7097d607

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
